namespace Slack.Client.Models.SlackApi
{
    public enum SlackActionIdEnum
    {
        profile_edit,
        profile_update,
        profile_receivers,
        profile_transmitters,
        profile_achievement_likes,
        profile_achievements_catalog,
        profile_create_news,
        profile_find_employee,
        profile_short_open_update,
        profile_short_open,
        profile_short_modal_subscribe,
        profile_short_modal_unsubscribe,
        profile_short_modal_like,
        profile_short_modal_unlike,
        profile_achievement_open,
        profile_achievement_close,
        profile_achievement_like, // Лайк ачивки
        profile_achievement_unlike, // Дизлайк ачивки
        profile_likes,
        profile_short_achievements,
        profile_show_comments,
        profile_create_feedback,
        create_comment,
        create_like,
        feed_list,
        feed_subscribe,
        feed_unsubscribe,
        short_feed_list,
        open_filter,
        search,
        select_male,
        select_female,
        select_male_or_female,
        select_comment_visibility,
        feed_achievement_open,
        feed_achievement_liked,
        search_all_achievement_types,
        search_create_news_achievement_types,
        search_employee,
        user_agreed,
        select_users_for_news,
        onboarding_create_news,
    }
}